// export { defaultConfig } from "./config";
// export { initAuth, getAuthConfig, AuthConfig } from "./config";
export { initAuth, getAuthConfig } from "./config/initAuth";
export type { AuthConfig } from "./config/config";
export * as utils from "./utils";
export * as components from "./components";
export * as routes from "./handlers";
export { AuthResponse } from "./utils";
export * as context from "./context";
export * as client from "./client";
export { AuthProvider } from "./context/AuthProvider";
export { SignInForm } from "./components/SignInForm";
export { TesterComponent } from "./test/TesterComponent";
